kind: Namespace
apiVersion: v1
metadata:
  name: ${namespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shofront
  namespace: ${namespace}
spec:
  selector:
    matchLabels:
      app: shofront
  replicas: 1
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: iad.ocir.io/orasenatdpltintegration03/shopfront:${BUILDRUN_HASH}
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - cat
            - echo "BUILD RUN"
            - echo ${BUILDRUN_HASH}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shopfront-app-service
  namespace: ${namespace}
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: shopfront-app